name: daily-metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:   
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.16
        with:
          filename: metrics.classic.svg
          markdown: https://raw.githubusercontent.com/lowlighter/metrics/master/source/templates/markdown/example.md
          token: ${{ secrets.READ_ME }}
          plugin_activity: yes
          plugin_activity_limit: 30
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
