name: daily-metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

jobs:   
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.16
        with:
          template: markdown
          filename: metrics.markdown.full.md
          markdown: https://raw.githubusercontent.com/lowlighter/metrics/master/source/templates/markdown/example.md
          config_output: markdown
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_posts: yes
          plugin_topics: yes
          plugin_topics_limit: 24
          plugin_isocalendar: yes
          plugin_languages: yes
          token: ${{ secrets.READ_ME }}
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120
